### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by pfeiflelukas** [CooleRRSA/crave-ng#10]
Hi Everyone,

I am running xubuntu on a raspberry pi 3 and i have downloaded the crave wallet ARM 32. When i run the ./craved it starts for about 15 seconds where everything works normal but then the server crashes with a segmentation fault. I cant get past this issue, am i doing something wrong?

Thanks

**Comment by pfeiflelukas** [comment]
Ok i will try to build from source. I did try this initially but this was before you pushed those new changes.

**Comment by CooleRRSA** [comment]
@pfeiflelukas Try to use special RPI2 build form new repository
https://github.com/Crave-Project/Crave-NG/releases

**Comment by pfeiflelukas** [comment]
@CooleRRSA All good that special RPI2 build seemed to work.

Keep up the good work
