### ISSUE TITLE
MN fails to start but wallet says Enabled

### ISSUE THREAD

**Issue by walkjivefly** [CooleRRSA/crave-ng#3]
I have 2 MNs which won't go active. They're sync'd and have lots of peers. They've been started from the wallet (manually from debug console) and show Enabled in My Masternodes and All Masternodes but the Active Time won't budge from zero (even after a few hours). I've restarted the daemons to no effect.
```
$ crave-cli masternode debug
Not capable masternode: Hot node, waiting for remote activation.

```
The debug logs show them checking themselves every 5 minutes and reaching the same conclusion.

Config and networking look good, these are drop-in replacements for 2 old-gen MNs. On restarting the wallet they list as Missing.

Created a masternode.conf on the VPS, restarted the daemon, masternode list-conf shows the expected configuration, it accepts a start command, the status shows as Enabled in list-conf but masternode debug still says waiting for remote activation. Starting from the wallet appears to work but the MN still says waiting for remote activation.

Dunno what else to try.

2 other drop-in replacements are working fine and collecting rewards. Their debug logs show the expected
`CActiveMasternode::EnableHotColdMasterNode() - Enabled! You may shut down the cold daemon.`
and
```
$ crave-cli masternode debug
Masternode successfully started
```

**Comment by CooleRRSA** [comment]
Hello. Try to enter in debug console
> "addnode ip:port onetry" where ip:port is ip and port of your remote masternode.
Run this command wor each masternode.
After this start your nodes.

**Comment by walkjivefly** [comment]
Thanks for the suggestion but it didn't help. They show as Enabled in the wallet, active time stuck at 0, the nodes themselves still say
`Not capable masternode: Hot node, waiting for remote activation.`

I tried running the wallet in gdb last night and tracing the CActiveMasternode execution. It surprised me and actually took the "Could not allocate vin" route. But then something funny (thread related?) happened and it locked up. 

I created a masternode.conf on the VPS and tried to start the masternode from there and got the "Could not allocate vin" error. I can see the coins locked against each of the addresses. The blockchain explorer built into the wallet doesn't show any transactions for either the working or not-working MN addresses.

I'll have another try with gdb later.

**Comment by walkjivefly** [comment]
Re-did the lock-in txns, re-did the addnodes, re-did the startmasternodes, still won't start. More gdb later.

**Comment by walkjivefly** [comment]
Not getting very far with gdb due to the multi-threading (and lack of knowledge on my part). Rebuilt with no optimisation, just in case. Made no difference. Still can't start 2 MNs and can't see why not.

**Comment by NYCrypto1** [comment]
I am setting up my 1st MN and I chose CRAVE. Not sure if that was the best decision because this recent swap has been a nightmare, to say the least.  What is going on CooleRRSA? I have only recieved 4000 new CRAVE Coins when I submitted 506 old Crave coins. Still waiting on the 1060 owed to me that I burned 2 days ago. Then to make things worse, I set up POS to at least get something started while I wait and the MAC OS High Sierra is wallet is nonfunctional.  I go ahead and set it up on a Windows OS and it works until you receive a stake of 4 CRAVE coins. Then the staking becomes inactive. WHAT IS GOING ON? Lets get it together boys.

**Comment by walkjivefly** [comment]
@NYCrypto1 Sorry to hear you've been having problems. For me the swap happened very smoothly and I was impressed with how well it went. I got in pretty early and I suspect @CooleRRSA is now getting a lot more requests and finding the manual system more problematic and time consuming. I expect he'll sort your coins out as soon as he can. I've been running Crave MNs for about 6 weeks and think you'll be happy with yours once it's running. You should probably deal with the incomplete swap via DM in Discord. Talk about the MacOS wallet and staking issues in Discord, possibly open new issues here in Github so others can find them and contribute to solving them. I've had 4 staking rewards since the coinswap with 20k coins in my wallet. Don't know how it determines which coins to stake, nor how often or for how long, nor how often we should expect rewards from staked coins but it appears one address gets the whole staking reward each block.

I finally have my troublesome 2 MNs running. I re-did everything again after getting inconclusive results running in gdb and, magically, the nodes went active this time. I have no idea why they refused so many times previously. The only reasonable explanation is that I was typing or copy'n'pasting something wrong (every time), no matter how improbable that seems.

**Comment by NYCrypto1** [comment]
Thanks walkjivefly for the reply. I believe that it will all work out soon enough. I have recieved 3 payouts in POS so far, but I am unsure if the "staking" has to be active at all times to continue to stake. Common sense says it must stay active, so we will see. I am more interested in the MN and I cant start one with 4000 coins.. uggghhh.. I believe this coin has a lot of potential and I am still excited to get started, but I just wish it was a more enjoyable experience to set up..
