### ISSUE TITLE
High Sierra not supported with this build

### ISSUE THREAD

**Issue by tregismoreira** [CooleRRSA/crave-ng#4]
I downloaded the new Crave wallet for Mac but got this error:

<img src="https://i.imgur.com/aYrjwON.png">

**Comment by CooleRRSA** [comment]
Test this release [https://github.com/CooleRRSA/crave-ng/releases/download/v2.5.0.1/Crave-2.5.0.1-osx64-highsierra.tar.gz](url)

**Comment by tregismoreira** [comment]
It worked, thanks!
