### ISSUE TITLE
MN going to missing

### ISSUE THREAD

**Issue by 2ge** [CooleRRSA/crave-ng#6]
Hi

using crave-qt 2.5.0.1 and mac (cold wallet setup) and on ubuntu server, got 2 masternodes running on same ip, different tx info and tx index only. After successful start one or both going to "Missing" state after some time (1 hour or so...)

How to solve this ?

Thanks.

**Comment by CooleRRSA** [comment]
Please go to official Discord channel in #live-support.

**Comment by 2ge** [comment]
thanks. problem seems, that is not possible to run 2 MN on same port. Source:
https://craveproject.net/pdf/Complete_Masternode_Guide_for_Crave_NextGen.pdf
